### ISSUE TITLE
Так работать не будет

### ISSUE THREAD

**Issue by SashaGHT** [SatSea/OAiP#1]
Не прописав свойство в форме, так работать не будет
https://github.com/SatSea/OAiP/blob/cc3c34b042c644e30b542f9b6e72ec701d433aad/Laba1_2OAiP/Form1.cs#L24

**Comment by SatSea** [comment]
Фикс уже летит

**Comment by SashaGHT** [comment]
> Фикс уже летит

Это? https://github.com/SatSea/OAiP/commit/bc5bafd2946338ebdfc1705d637e24780e870753

**Comment by SatSea** [comment]
Ну как видишь, да

**Comment by SashaGHT** [comment]
> Ну как видишь, да

Ничего там не видно, потому что ты мусор пушишь в ветку
